name: Update Deep-ML Stats in README

on:
  schedule:
    # Runs every day at 08:00 UTC. Adjust the cron schedule as needed.
    # See: https://crontab.guru/
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      # Give the workflow contents write permission to commit to the repo
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # Checks out your repository code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Specify Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        # Optional: Pass the profile URL as an environment variable if you want to make it configurable
        # env:
        #   PROFILE_URL: "https://www.deep-ml.com/profile/Y5llgZoBWpPVmkyEw0guauFb8IG2"
        run: python update_deepml_stats.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]' # Use the Actions bot user
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Check if README.md was modified
          if git diff --quiet README.md; then
            echo "No changes to commit."
            exit 0 # Exit cleanly if no changes
          fi
          git add README.md
          git commit -m "Automated update: Deep-ML stats"
          # Add error handling for the push
          if git push; then
            echo "Changes pushed successfully."
          else
            echo "Failed to push changes. Maybe the branch is protected or credentials issue?"
            exit 1 # Exit with error if push fails
          fi
        # Optional: Add specific error handling or notifications here if push fails